version: "3.9"
services:
  web:
    build: .
    depends_on:
      - redis
    ports:
      - "8000:8000"
    command:
      sh -c "python djchannels/manage.py migrate &&
             python djchannels/manage.py runserver 0.0.0.0:8000"
  redis:
    image: "redis"
